### ISSUE TITLE
请问本项目开源吗？哪里可以拿到测试demo

### ISSUE THREAD

**Issue by xiaoyaomimi** [zeusees/HyperFAS#1]

**Comment by lsy17096535** [comment]
你好，我们开始准备把模型开源的，但是遇到了泛化能力差的问题，换不同场景效果下降较多，就没有开源，继续完善模型，我们没有停止这个项目的开发，有一定进展我们会开源模型。

**Comment by lsy17096535** [comment]
@xiaoyaomimi 提交了第一版代码。

**Comment by paleomoon** [comment]
@lsy17096535 大佬，能否简要说说用的什么模型架构（mobilenet v?），做了哪些优化工作？菜鸟做不动了，恳请指点一二，非常感谢！

**Comment by lsy17096535** [comment]
mobilenet-0.5 v1 为了转化方便 relu6改成了relu ，别的没啥变化。
