### ISSUE TITLE
使用摄像头还是数据集都没办法得到nrof_faces>0的值

### ISSUE THREAD

**Issue by Hisssec** [zeusees/HyperFAS#19]
作者你好！我现在正在复现源码，不过出现了一个问题是不管我使用摄像头还是生成的数据集都没办法得到nrof_faces>0的值，以至于直接跳出if语句了，分数指标也没办法算了。这块，请问您有什么解决办法吗[疑问]
![IMG_20231006_193930](https://github.com/zeusees/HyperFAS/assets/139356718/ac84e804-786e-435f-909a-e5711b86c4b5)

**Comment by delong-zhu** [comment]
> 作者你好！我现在正在复现源码，不过出现了一个问题是不管我使用摄像头还是生成的数据集都没办法得到nrof_faces>0的值，以至于直接跳出if语句了，分数指标也没办法算了。这块，请问您有什么解决办法吗[疑问] !
