### ISSUE TITLE
效果不太理想

### ISSUE THREAD

**Issue by xuguozhi** [zeusees/HyperFAS#6]
实际测试了，发现对于纸张有一定效果，但是真人50%-50%的概率，靠阈值起不到太大作用。但依旧很感谢开源模型

**Comment by netdrop-sys** [comment]
是的，效果还是需要提高，泛化能力不好，我们最近在测试一个新的算法，效果好的话会开源出来。

**Comment by xuguozhi** [comment]
开源虽然短时间没有经济收益，但是伟大的项目都是从开源开始，吸引众多开发者一同完善。希望你们继续努力，持续关注中

**Comment by netdrop-sys** [comment]
多谢理解，我们会继续完善这个版本，等提交新的模型会继续给您回复。

**Comment by cana-jianbin** [comment]
> 是的，效果还是需要提高，泛化能力不好，我们最近在测试一个新的算法，效果好的话会开源出来。

本来是我正要做的事情，余大佬的CDC，只是我是工程弱鸡。虽然测试结果不理想，谢谢了。（速度还挺快的，而且可以同时鉴别多张人脸）

**Comment by netdrop-sys** [comment]
我们下个月争取提交一个新的版本，欢迎来测试。

**Comment by lucaslu1987** [comment]
> 我们下个月争取提交一个新的版本，欢迎来测试。

大佬要更新了么

**Comment by luan1412167** [comment]
> We are striving to submit a new version next month and welcome to test it.

Did you release a new version?
