### ISSUE TITLE
ValueError: Unknown layer: DepthwiseConv2D

### ISSUE THREAD

**Issue by shuyikong** [zeusees/HyperFAS#9]
请问用的是什么版本的tf和keras呀，我运行会报这个错，请问有解决方法吗

**Comment by netdrop-sys** [comment]
我们这里tf版本是1.13.1，keras版本是2.2.4。

**Comment by shuyikong** [comment]
换了版本后可以运行了~谢谢 :) 只是效果不太理想，用手机里的清晰大头人像很多被判为真人……

**Comment by shuyikong** [comment]
换了版本后可以运行了~谢谢 :) 只是效果不太理想，用手机里的清晰大头人像很多被判为真人……

**Comment by netdrop-sys** [comment]
@shuyikong 是的，我们自己也明白，但是我们的数据没办法跟大厂比拼，只能一点一点完善，但是这个项目不会停下来，等我们丰富了数据，会继续提交新的模型。

**Comment by fzupang** [comment]
感谢，帮助很大
